### ISSUE TITLE
mapd installation on 16.04.1-Ubuntu is failing.

### ISSUE THREAD

**Issue by UllasShanthakumar** [omnisci/mapd-core#254]
Hi Team,

We were trying to install the mapd on a Ubuntu 16.04.1 server with the latest source available in git and the build is failing.
We have git cloned the mapd repository and are following the instructions as suggested.
On July 23rd we had git cloned the mapd repository and then went through the complete build process and was successful.

Here is the error message which we see when the make failed.
Command which was executed was. : 

make -j 10
/usr/include/boost/variant/variant.hpp:1555:38: error: call of overloaded 'initialize(void*, boost::move_detail::remove_reference<long int&>::type)' is ambiguous
               initializer::initialize(
                                      ^

The complete installation log has been uploaded for reference : 
[mapd_installation_20180731_030008.log.gz](https://github.com/mapd/mapd-core/files/2245040/mapd_installation_20180731_030008.log.gz)

Below the script which does the installation 
[install_mapd.sh.gz](https://github.com/mapd/mapd-core/files/2245046/install_mapd.sh.gz)

Feel free to let us know if there are any gaps in our understanding.

Looking forward for assistance.

With Regards
Ullas Shanthakumar.

**Comment by alexbaden** [comment]
Hi Ullas,

You are correct, a build issue on Ubuntu 16.04 popped up recently. We are working to resolve the issue and hope to have something in the next few days. In the meantime, I would suggest using 18.04 or building inside a Docker container on your 16.04 installation. You can use nvidia-docker2 (https://github.com/NVIDIA/nvidia-docker) if you want CUDA support. Executing the mapd-deps script for Ubuntu in the docker container should get you all the dependencies you need.

I will let you know here when we have a fix.

**Comment by UllasShanthakumar** [comment]
Hi Alex,
Thanks for the suggestion.
We have created container with 'nvidia/cuda:9.1-devel-ubuntu16.04' docker image and built mapd-core from source. But we have faced the exact same build failure reported in this issue. Please let us know if any work around is available or when this issue may be fixed. Kindly note that we are in the middle of evaluating MAPD for our solution and hit a roadblock here. Appreciate your support.

With Regards
Ullas Shanthakumar.

**Comment by andrewseidl** [comment]
Hi Ullas,

The issue is with the older version of Boost and/or GCC in 16.04. You shouldn't have issues if you instead use the `nvidia/cuda:9.2-devel-ubuntu18.04` image. (Note: they have only posted CUDA 9.2 images for Ubuntu 18.04, so you must have recent drivers which support 9.2).

Alternatively I've started pushing the containers we use for our internal builds. See https://hub.docker.com/r/mapd/core-build-centos7-cuda9.0/ for usage.

Even though the image is based on CentOS, the `-DPREFER_STATIC_LIBS=on` option instructs the build to static link in all dependencies. Meaning: you can build on CentOS but run on Ubuntu, and you only need to install Java and the NVIDIA drivers. We use CPack to generate packages so you can use, for example, `cpack -G DEB` to generate a `.deb` to install on Ubuntu.

**Comment by andrewseidl** [comment]
Quick update: you might want to build the deps image yourself instead of pulling it off of Docker Hub. There appears to be an issue with the versioned CUDA/driver libs, which causes linking issues if you have a different driver version than I used to generate the image.

Something like:

```
git clone https://github.com/mapd/mapd-core
pushd mapd-core/docker/build/centos7
docker build -t mapd/core-build .
popd
docker run --runtime nvidia --rm -it -u $(id -u):$(id -g) -v $PWD/mapd-core:/mapd-core mapd/core-build bash
cd /mapd-core
source /etc/profile.d/modules.sh
module load cuda
module load mapd-deps
mkdir build && cd build
cmake -DPREFER_STATIC_LIBS=on -DCMAKE_BUILD_TYPE=release ..
make -j $(nproc)
make sanity_tests
cpack -G TGZ
# cpack -G RPM # for .rpm
# cpack -G DEB # for .deb
```

**Comment by alexbaden** [comment]
Hi Ullas,

Sorry for the delay in my reply -- I was able to modify our build script and get a custom build of boost going in an ubuntu 16.04 container. I have attached a very early version of the script here. Note that this may conflict with system boost, but in a fresh `ubuntu:16.04` docker container running this script allowed me to build mapd_server without issue.

Hope this helps,
Alex
[mapd-deps-ubuntu-16.04.sh.tar.gz](https://github.com/mapd/mapd-core/files/2259213/mapd-deps-ubuntu-16.04.sh.tar.gz)

**Comment by randyzwitch** [comment]
Marking this closed, if only because the solutions are not OmniSci related per se, but rather making sure that the proper compiler and library versions are set. In general, OmniSci recommends using Ubuntu 18.04LTS going forward, or using the containers pushed by OmniSci as referenced by @andrewseidl
