### ISSUE TITLE
Inconsistency in num tuples within fragment

### ISSUE THREAD

**Issue by jeremyvillalobostaste** [omnisci/mapd-core#275]
The table fail into this state after inserting document using SQL INSERT
for thousands of documents. 

The computer running the test database may ran out of space.  
The table does not seem to be recoverable.  
But other table still work.

The table cannot be dropped either

**Comment by senatorgrant** [comment]
@jeremyvillalobostaste  have you identified the inconsistencies already? can you give us a sample of the dataset?

**Comment by senatorgrant** [comment]
@jeremyvillalobostaste can you give us any more information? have you figured out where the inconsistency exists? can you provide a sample of your data?
that error message is produced [here]([https://github.com/omnisci/mapd-core/blob/75853e87efd32e26ad1270a59745a2b33269bfde/Fragmenter/InsertOrderFragmenter.cpp#L125]) if that helps you figure out where the problem might be.

**Comment by jeremyvillalobostaste** [comment]
I will try to reproduce the error with data I can share .
I also notice the mapd data folder grew to a huge number ( 88GB )

**Comment by randyzwitch** [comment]
Hi @jeremyvillalobostaste - 

Are you still having an issue with this or can this issue be closed?

Thanks,
Randy

**Comment by alexbaden** [comment]
Hi @jeremyvillalobostaste,

We identified some areas in our storage layer where we would see inconsistencies in a table when the underlying filesystem was full. The issues affect our storage layer's ability to checkpoint. We believe we have resolved these issues and that commit should make it's way to this repository shortly. If you have an effected table, you can roll back the table epoch using the command `\ste "<<tablename>> <<epochval>>"` in `mapdql`. Table epochs are shown at startup with verbose logging enabled (`export GLOG_v=1` ) and can also be read directly out of the `epoch` file in the table data directory using `od`, e.g. `od -i epoch`. We recommend incrementally backing the epoch value by 1 until the problem is resolved.

Note that moving the table epoch manually **will result in data loss**, as the metadata pages above that epoch will be rewritten. Backing up your data directory first is always a good idea before changing table epoch values.

**Comment by alexbaden** [comment]
Closed with 8c42dda28bdf624d8333197d6c6814289ae178ab
