### ISSUE TITLE
Any APIs to call for a third-party program? 

### ISSUE THREAD

**Issue by pflee2002** [omnisci/mapd-core#289]
I am very new to this product. So I wish to call the MapD api to manipulate a database from my own c++/python CUDA program. Is it possible?  Thanks

**Comment by senatorgrant** [comment]
Certainly. We have several connectors. I recommend [pymapd](https://github.com/omnisci/pymapd) for python applications.

**Comment by randyzwitch** [comment]
@pflee2002 To give a little more context to @senatorgrant's answer, MapD Core uses Apache Thrift to communicate between the client and the database. We currently provide a pymapd for interacting via Python, a JavaScript connector, JDBC, Julia...but this list is really only limited to the languages that can interact via Thrift. 

So if you wanted to use C++, you could generate [Apache Thrift](https://thrift.apache.org/) bindings to OmniSci, then interact via C++. But since you referenced Python, I would start with pymapd, which besides already existing also has some CUDA support via pygdf and the [GOAI](http://gpuopenanalytics.com/#/)/[RAPIDS](https://rapids.ai/) NVIDIA projects.

**Comment by pflee2002** [comment]
Thanks @randyzwitch and @senatorgrant 
We have two groups of persons using Python and C++ respectively. We will start using Python first but C++ will be necessary to combine with MPI o a computer clusters later. 
Do you also provide example codes in Python programming?  Thanks again.

**Comment by randyzwitch** [comment]
Our pymapd documentation is located at https://pymapd.readthedocs.io/en/latest/.

Closing this issue out since it seems like it's solved. Please feel free to continue the discussion on our [community board](https://community.omnisci.com/), where other members of the community (including OmniSci employees) will be able to help with how to use pymapd effectively.
