### ISSUE TITLE
[qeustion] - Storage layout/limitation 

### ISSUE THREAD

**Issue by archenroot** [omnisci/mapd-core#293]
Hi, I would like to test Mapd in scenario where data set will be larger then total GPU memory on node:
1. Can I have data set which doesn't fit into memory completely or Mapd is simply engine where data always need to fit in memory?
2. Assuming i can load more data into mapd table then gpu total memory available, I understand that there must happen some kind of streaming. Do you support such streaming? 
3. Do you support some heavy compression algorithm to save IO? GPU is great in fast decompression, so when you load compressed chunks, you save IO time and decompression will be much faster on GPU. Do you have such algo in place, or do you plan to support one, it could especially save cold start query.

Thank you for answer.

**Comment by randyzwitch** [comment]
> Can I have data set which doesn't fit into memory completely or Mapd is simply engine where data always need to fit in memory?

Yes, you can have a dataset that doesn't fit inside of GPU memory. OmniSci is a columnar-oriented database, which means that we only load the columns of data specified in the query to do computations. This not only saves space, but allows for much higher performance for analytics workloads.

If you specify a query using a large number of columns that doesn't fit completely into GPU, OmniSci tries to fall back to CPU to cache the columns, then does the computations by putting as much into the GPU as it can, then when the calculation is done, it brings different data into the GPU and so on until the query is completed. Because of this property, we recommend having 4-8x the amount of CPU RAM as GPU RAM, so that you don't have a resource issue.

Of course, if you have a gigantic amount of data, eventually OmniSci will give you an out-of-memory error before it runs the query when it believes the query can't be calculated. At this point, there's nothing to do but add more hardware.

> Assuming i can load more data into mapd table then gpu total memory available, I understand that there must happen some kind of streaming. Do you support such streaming?

"Streaming" is probably not the right term for this operation. If I understand what you are asking, yes, OmniSci will manage reading the data from disk into GPU and CPU memory automatically, the user doesn't need to worry about memory management.

In terms of streaming data, such as data continuously arriving via sensors or API calls or the like, yes OmniSci supports that. For an illustrative example, see this blog post about ingesting streaming data from Kafka into OmniSci: https://www.jowanza.com/blog/2018/9/8/real-time-station-tracking-ford-gobike-and-mapd

> Do you support some heavy compression algorithm to save IO? GPU is great in fast decompression, so when you load compressed chunks, you save IO time and decompression will be much faster on GPU. Do you have such algo in place, or do you plan to support one, it could especially save cold start query.

Yes, OmniSci uses compression as it makes sense. All of our low-level C++/CUDA engineers are constantly looking for the most optimal way to structure and use data to obtain the highest performance for a given set of hardware.
